CROP_NAME_TO_NUMBER = {
    'rice': 58,
    'sapota': 62,
    'castor seed': 13,
    'cabbage': 11,
    'cotton(lint)': 17,
    'jute': 74,
    'lemon': 49,
    'soyabean': 43,
    'cowpea(lobia)': 57,
    'samai': 60,
    'pomegranate': 39,
    'sunflower': 67,
    'sesamum': 63,
    'ragi': 56,
    'jowar': 28,
    'banana': 3,
    'grapes': 35,
    'mango': 42,
    'turmeric': 72,
    'onion': 41,
    'potato': 54,
    'brinjal': 6,
    'sweet potato': 68,
    'garlic': 49,
    'coriander': 16,
    'black pepper': 7,
    'beans & mutter(vegetable)': 65,
    'sugarcane': 66,
    'orange': 76,
    'papaya': 44,
    'cashewnut': 12,
    'coconut': 15,
    'ginger': 39,
    'paddy': 75,
    'maize': 34,
    'wheat': 75,
    'moong(green gram)': 38,
    'gram': 24,
    'pineapple': 51,
    'barley': 30,
    'peas & beans (pulses)': 55,
    'groundnut': 26
}
