# Generated by Django 4.2.18 on 2026-01-18 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.URLField(default='https://cdn-icons-png.flaticon.com/128/149/149071.png'),
        ),
    ]
