# Generated by Django 4.2.18 on 2026-01-19 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='landmark',
            name='location_details',
            field=models.JSONField(default=list),
        ),
    ]
