# Generated by Django 4.2.18 on 2026-01-18 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_profile_pic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CRS', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FertilizerRecommendationRequest',
            fields=[
                ('requestId', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('moisture', models.FloatField()),
                ('soil_type', models.CharField(max_length=50)),
                ('crop_type', models.CharField(max_length=100)),
                ('nitrogen', models.FloatField()),
                ('phosphorous', models.FloatField()),
                ('potassium', models.FloatField()),
                ('fertilizer', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('landId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.landmark')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
