# Generated by Django 4.2.18 on 2026-01-19 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRS', '0003_fertilizerrecommendationrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='previouscroprequest',
            name='month',
        ),
    ]
